version: '3'

services:
  strapi:
    container_name: strapi_cms
    image: strapi/strapi
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=strapi
      - DATABASE_PASSWORD=strapi
    ports:
      - 1337:1337
    volumes:
      - ./strapi:/srv/app
    # command: npm install --verbose
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi

  next.js:
    container_name: next.js
    image: node:16-alpine
    ports:
      - 3000:3000
    volumes:
      - ./app/:/app
    working_dir: /app
    command: npm start